apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cfs-quota-bug-test-without-quota
  labels:
    app.kubernetes.io/name: cfs-quota-bug-test-without-quota
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cfs-quota-bug-test-without-quota
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cfs-quota-bug-test-without-quota
    spec:
      containers:
        - image: seanshahkarami/cfs-quota-bug-test
          name: cfs-quota-bug-test-without-quota
          args: ["-iterations", "1000", "-sleep", "1000ms"]
